spring:
  datasource:
    url: jdbc:mysql://kdt.goodee.co.kr:20003/mysql?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update  # 운영은 validate 또는 none 권장
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

logging:
  level:
    org.springframework: INFO